#!/bin/sh

# PROVIDE: nsqadmin
# REQUIRE: LOGIN
# BEFORE:  networking
# KEYWORD: shutdown

# Add the following line to /etc/rc.conf to enable `nsqadmin':
#
#nsqadmin_enable="YES"

. /etc/rc.subr

name="nsqadmin"
rcvar="${name}_enable"

command="/usr/local/bin/${name}"
command_args="--lookupd-http-address={{ nsqlookupd_address }}:4161"

start_cmd="/usr/sbin/daemon -f -u op -c $command $command_args"

load_rc_config "$name"
: ${nsqadmin_enable="NO"}

run_rc_command "$1"
