#!/bin/sh

# PROVIDE: nsqd
# REQUIRE: LOGIN
# BEFORE:  networking
# KEYWORD: shutdown

# Add the following line to /etc/rc.conf to enable `nsqd':
#
#nsqd_enable="YES"

. /etc/rc.subr

name="nsqd"
rcvar="${name}_enable"

command="/usr/local/bin/${name}"
command_args="--lookupd-tcp-address={{ nsqlookupd_address }}:4160 --data-path=/data/nsqd"

start_cmd="/usr/sbin/daemon -f -u op -c $command $command_args"

load_rc_config "$name"
: ${nsqd_enable="NO"}

run_rc_command "$1"

