- hosts: all
  vars:
    - instance_hostname: "{{ ansible_hostname }}"
  roles:
    - common

- hosts: bdmhack-workbench
  vars:
    nsqlookupd_address: "{{ hostvars['workbench.bdmhack']['ansible_ssh_host'] }}"
  roles:
    - golang
    - nsq
  tasks:
    - name: Install jq
      pkgng: name=jq state=present
      sudo: true
    - name: Enable nsqlookupd at startup
      sysrc: name=nsqlookupd_enable state=present value=YES
      sudo: true
    - name: Enable nsqadmin at startup
      sysrc: name=nsqadmin_enable state=present value=YES
      sudo: true

- hosts: bdmhack-producer
  vars:
    nsqlookupd_address: "{{ hostvars['workbench.bdmhack']['ansible_ssh_host'] }}"
  roles:
    - golang
    - nsq
  tasks:
    - name: Enable nsqd at startup
      sysrc: name=nsqd_enable state=present value=YES
      sudo: true


